create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
create table tasks (account_id bigint not null, id bigint not null, task_desc varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, username varchar(100) not null, email_address varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table tasks_seq (next_val bigint) engine=InnoDB;
insert into tasks_seq values ( 1 );
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table tasks add constraint FKo9mhbrivt80l2b25kf71f32ka foreign key (account_id) references users (id);
