alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
alter table tasks drop foreign key FKo9mhbrivt80l2b25kf71f32ka;
drop table if exists tasks;
drop table if exists users;
drop table if exists tasks_seq;
drop table if exists users_seq;
